# Identificator for Simulation/Export
ID: STARGAZE # ID used for simulation run and export
# Input Options
location: Campo Militar de Santa Margarida # ID for location file at which simulation shall be executed
motors: [M1670-P] # IDs of used motors (multiple for comparison) for simulation
parachutes: [stargaze-main, stargaze-drogue] # IDs of parachutes to add to rocket
dateDiff: 7 # day difference relative to today for which simulation shall be executed
railL: 4 # launch rail length in meter
inclination: 84 # launch inclination from ground in degree
heading: 0 # launch heading relative to north in degree
dragCurvePowerOnFile: None # optional!; name of file with drag curve for rocket with power on
dragCurvePowerOffFile: None # optional!; name of file with drag curve for rocket with power off
diameter: 0.1236 # diameter of the rocket in m
launch_date: 2025-10-12_12-00-00

# Export Options: Environment
exportTextEnvironment: True
exportPlotEnvironment: True
# Export Options: Motor
exportTextMotor: True
exportPlotThrust: True
# Export Options: Rocket
exportPlotStaticMargin: True
exportPlotRocket: True
# Export Options: Simulation
exportTextSimulation: True
exportPlotTrajectory3D: True
exportPlotLinearKinematicData: True
exportPlotFlightPathAngleData: True
exportPlotAttitudeData: True
exportPlotAngularKinematicsData: True
exportPlotAerodynamicForces: True
exportPlotRailButtonsForces: True
exportPlotEnergyData: True
exportPlotFluidMechanicsData: True
exportPlotStabilityAndControlData: True
exportPlotPressureRocketAltitude: True
exportPlotPressureSignals: True
# Export Options: Analysis
exportRawFlightData: True
exportFlightData: True
exportFlightDataTimeStepSeconds: 0.01
exportTrajectoryForGoogleEarth: True
