repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.6
  hooks:
  - id: insert-license
    name: Insert license headers (shell-style comments)
    files: '(?:^|/)(?:.*\.(?:ps1|py|sh|toml)|Dockerfile|Makefile)$'
    args:
      - --detect-license-in-X-top-lines=15
      - --license-filepath
      - license_header.txt
      - --comment-style
      - '#'
      - --use-current-year
  - id: remove-crlf

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.17
  hooks:
  - id: ruff
    args: [ --select, I, --fix ]
  - id: ruff-format
